/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTimingRouteImport } from './routes/_authenticated/timing'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedStrategieRouteImport } from './routes/_authenticated/strategie'
import { Route as AuthenticatedStatistiquesRouteImport } from './routes/_authenticated/statistiques'
import { Route as AuthenticatedReglagesRouteImport } from './routes/_authenticated/reglages'
import { Route as AuthenticatedReelsRouteImport } from './routes/_authenticated/reels'
import { Route as AuthenticatedIdeesRouteImport } from './routes/_authenticated/idees'
import { Route as AuthenticatedCorbeilleRouteImport } from './routes/_authenticated/corbeille'
import { Route as AuthenticatedConcurrentsRouteImport } from './routes/_authenticated/concurrents'
import { Route as AuthenticatedCalendrierRouteImport } from './routes/_authenticated/calendrier'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimingRoute = AuthenticatedTimingRouteImport.update({
  id: '/timing',
  path: '/timing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStrategieRoute = AuthenticatedStrategieRouteImport.update({
  id: '/strategie',
  path: '/strategie',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatistiquesRoute =
  AuthenticatedStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReglagesRoute = AuthenticatedReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReelsRoute = AuthenticatedReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdeesRoute = AuthenticatedIdeesRouteImport.update({
  id: '/idees',
  path: '/idees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCorbeilleRoute = AuthenticatedCorbeilleRouteImport.update({
  id: '/corbeille',
  path: '/corbeille',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConcurrentsRoute =
  AuthenticatedConcurrentsRouteImport.update({
    id: '/concurrents',
    path: '/concurrents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendrierRoute = AuthenticatedCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/concurrents': typeof AuthenticatedConcurrentsRoute
  '/corbeille': typeof AuthenticatedCorbeilleRoute
  '/idees': typeof AuthenticatedIdeesRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/reglages': typeof AuthenticatedReglagesRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/strategie': typeof AuthenticatedStrategieRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/timing': typeof AuthenticatedTimingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/concurrents': typeof AuthenticatedConcurrentsRoute
  '/corbeille': typeof AuthenticatedCorbeilleRoute
  '/idees': typeof AuthenticatedIdeesRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/reglages': typeof AuthenticatedReglagesRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/strategie': typeof AuthenticatedStrategieRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/timing': typeof AuthenticatedTimingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/calendrier': typeof AuthenticatedCalendrierRoute
  '/_authenticated/concurrents': typeof AuthenticatedConcurrentsRoute
  '/_authenticated/corbeille': typeof AuthenticatedCorbeilleRoute
  '/_authenticated/idees': typeof AuthenticatedIdeesRoute
  '/_authenticated/reels': typeof AuthenticatedReelsRoute
  '/_authenticated/reglages': typeof AuthenticatedReglagesRoute
  '/_authenticated/statistiques': typeof AuthenticatedStatistiquesRoute
  '/_authenticated/strategie': typeof AuthenticatedStrategieRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/timing': typeof AuthenticatedTimingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/calendrier'
    | '/concurrents'
    | '/corbeille'
    | '/idees'
    | '/reels'
    | '/reglages'
    | '/statistiques'
    | '/strategie'
    | '/studio'
    | '/timing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/calendrier'
    | '/concurrents'
    | '/corbeille'
    | '/idees'
    | '/reels'
    | '/reglages'
    | '/statistiques'
    | '/strategie'
    | '/studio'
    | '/timing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/calendrier'
    | '/_authenticated/concurrents'
    | '/_authenticated/corbeille'
    | '/_authenticated/idees'
    | '/_authenticated/reels'
    | '/_authenticated/reglages'
    | '/_authenticated/statistiques'
    | '/_authenticated/strategie'
    | '/_authenticated/studio'
    | '/_authenticated/timing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timing': {
      id: '/_authenticated/timing'
      path: '/timing'
      fullPath: '/timing'
      preLoaderRoute: typeof AuthenticatedTimingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategie': {
      id: '/_authenticated/strategie'
      path: '/strategie'
      fullPath: '/strategie'
      preLoaderRoute: typeof AuthenticatedStrategieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistiques': {
      id: '/_authenticated/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof AuthenticatedStatistiquesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reglages': {
      id: '/_authenticated/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof AuthenticatedReglagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reels': {
      id: '/_authenticated/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedReelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/idees': {
      id: '/_authenticated/idees'
      path: '/idees'
      fullPath: '/idees'
      preLoaderRoute: typeof AuthenticatedIdeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/corbeille': {
      id: '/_authenticated/corbeille'
      path: '/corbeille'
      fullPath: '/corbeille'
      preLoaderRoute: typeof AuthenticatedCorbeilleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/concurrents': {
      id: '/_authenticated/concurrents'
      path: '/concurrents'
      fullPath: '/concurrents'
      preLoaderRoute: typeof AuthenticatedConcurrentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendrier': {
      id: '/_authenticated/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof AuthenticatedCalendrierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendrierRoute: typeof AuthenticatedCalendrierRoute
  AuthenticatedConcurrentsRoute: typeof AuthenticatedConcurrentsRoute
  AuthenticatedCorbeilleRoute: typeof AuthenticatedCorbeilleRoute
  AuthenticatedIdeesRoute: typeof AuthenticatedIdeesRoute
  AuthenticatedReelsRoute: typeof AuthenticatedReelsRoute
  AuthenticatedReglagesRoute: typeof AuthenticatedReglagesRoute
  AuthenticatedStatistiquesRoute: typeof AuthenticatedStatistiquesRoute
  AuthenticatedStrategieRoute: typeof AuthenticatedStrategieRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedTimingRoute: typeof AuthenticatedTimingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendrierRoute: AuthenticatedCalendrierRoute,
  AuthenticatedConcurrentsRoute: AuthenticatedConcurrentsRoute,
  AuthenticatedCorbeilleRoute: AuthenticatedCorbeilleRoute,
  AuthenticatedIdeesRoute: AuthenticatedIdeesRoute,
  AuthenticatedReelsRoute: AuthenticatedReelsRoute,
  AuthenticatedReglagesRoute: AuthenticatedReglagesRoute,
  AuthenticatedStatistiquesRoute: AuthenticatedStatistiquesRoute,
  AuthenticatedStrategieRoute: AuthenticatedStrategieRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedTimingRoute: AuthenticatedTimingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
